cssDir: stylesheets
imgDir: images
tmDir: trademarks
jsDir: javascripts
fontsDir: fonts

defaults:
  title: Default project page title
	
links:
  home: http://www.jboss.org
  blogs: http://planet.jboss.org
  tweets: http://twitter.com/#!/jbossdeveloper 
  facebook: http://www.facebook.com/jboss
  twitter: http://jboss.org/twitter
  linkedIn: http://www.linkedin.com/company/jboss
  vimeo: http://vimeo.com/jbossdeveloper
  asylum: http://asylum.libsyn.com/
  events: http://www.jboss.org/events
  getStarted: http://www.jboss.org/developer
  getToolKit: http://devstudio.jboss.com/download/
  downloads: http://downloads.jboss.org/
  documentation: http://docs.jboss.org/
  forums: http://community.jboss.org/
  webinars: http://www.jboss.org/webinars
  articles: http://java.dzone.com/category/tags/jboss
  books: http://www.jboss.org/books
  getInvolved: http://www.jboss.org/contribute
  wiki: http://community.jboss.org/
  discussions: http://community.jboss.org/
  issueTracker: http://issues.jboss.org/
  sourceRepos: http://source.jboss.org/
  userGroups: http://www.jboss.org/usergroups
  sigs: http://jboss.org/interests
  reportSecurityIssue: http://www.jboss.org/security
  projects: http://www.jboss.org/projects
  appServer: http://www.jboss.org/jbossas
  webServer: http://www.jboss.org/jbossweb
  gateIn: http://www.jboss.org/gatein
  esb: http://www.jboss.org/jbossesb
  drools: http://www.jboss.org/drools
  hibernate: http://www.hibernate.org/
  richfaces: http://www.jboss.org/richfaces
  tools: http://www.jboss.org/tools
  rhq: http://www.jboss.org/rhq
  products: http://www.redhat.com/products/jbossenterprisemiddleware
  appPlatform: http://www.redhat.com/products/jbossenterprisemiddleware/application-platform
  webPlatform: http://www.redhat.com/products/jbossenterprisemiddleware/web-platform
  portalPlatform: http://www.redhat.com/products/jbossenterprisemiddleware/portal
  soaPlatform: http://www.redhat.com/products/jbossenterprisemiddleware/soa
  brms: http://www.redhat.com/products/jbossenterprisemiddleware/business-rules
  dataServicesPlatform: http://www.redhat.com/products/jbossenterprisemiddleware/data-services
  wfk: http://www.redhat.com/products/jbossenterprisemiddleware/web-framework-kit
  devStudio: http://www.redhat.com/products/jbossenterprisemiddleware/developer-studio
  operationsNetwork: http://www.redhat.com/products/jbossenterprisemiddleware/operations-network
	