title: JBoss Community

css_minifier: disabled
js_minifier: disabled
html_minifier: disabled

fileMerger:
  enabled: true
  outputFilePath: /javascripts/bootstrap-community.js
  paths:
    - /javascripts/_bootstrap-transition.js
    - /javascripts/_bootstrap-alert.js
    - /javascripts/_bootstrap-button.js
    - /javascripts/_bootstrap-carousel.js
    - /javascripts/_bootstrap-collapse.js
    - /javascripts/_bootstrap-dropdown.js
    - /javascripts/_bootstrap-modal.js
    - /javascripts/_bootstrap-tooltip.js
    - /javascripts/_bootstrap-popover.js
    - /javascripts/_bootstrap-scrollspy.js
    - /javascripts/_bootstrap-tab.js
    - /javascripts/_bootstrap-typeahead.js
    - /javascripts/_bootstrap-affix.js
    - /javascripts/_jbossorg-navbarfix.js
    - /javascripts/_jbossorg-misc.js

wget:
  enabled: true
  createGitIgnoreFiles: true
  options:
    - --no-remove-listing
    - -q
    - -r
    - --no-parent
    - -N
    - --reject 'index.html*'
    - -e robots=off
    - --directory-prefix=cache
  urls:
    - http://static-stg.jboss.org/theme/js/libs/jquery/1.8.1/jquery.js
    - http://static-stg.jboss.org/theme/js/libs/jquery/1.8.1/jquery.min.js
    - http://static-stg.jboss.org/theme/js/libs/html5/pre3.6/html5.min.js
    - http://static-stg.jboss.org/theme/js/libs/prettify/188.0.0/prettify.min.js
    - http://static-stg.jboss.org/theme/js/libs/holder/1.9/holder.js
    - http://static-stg.jboss.org/theme/fonts/titilliumtext/
    - http://static-stg.jboss.org/theme/images/common/
    - http://static-stg.jboss.org/theme/images/community/
    - http://static-stg.jboss.org/theme/images/tools/

profiles:
  development:
    jborg_fonts_url: /cache/static-stg.jboss.org/theme/fonts
    jborg_images_url: /cache/static-stg.jboss.org/theme/images
    jborg_js_url: /cache/static-stg.jboss.org/theme/js
    bootstrap_css_url: /stylesheets
    bootstrap_js_url: /javascripts
  staging:
    jborg_fonts_url: http://static-stg.jboss.org/theme/fonts
    jborg_images_url: http://static-stg.jboss.org/theme/images
    jborg_js_url: http://static-stg.jboss.org/theme/js
    bootstrap_css_url: http://static-stg.jboss.org/theme/css/bootstrap/2.2.2.0.0
    bootstrap_js_url: http://static-stg.jboss.org/theme/js/libs/bootstrap/2.2.2.0.0
    base_url: http://design-stg.jbossorg/boostrap/themes
  production:
    minified: .min
    jborg_fonts_url: http://static.jboss.org/theme/fonts
    jborg_images_url: http://static.jboss.org/theme/images
    jborg_js_url: http://static.jboss.org/theme/js
    bootstrap_css_url: http://static.jboss.org/theme/css/bootstrap/2.2.2.0.0
    bootstrap_js_url: http://static.jboss.org/theme/js/libs/bootstrap/2.2.2.0.0
    base_url: http://design.jbossorg/boostrap/themes
